# SPDX-FileCopyrightText: (c) 2025 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Query k3s installed version
  register: _k3s_version_query
  changed_when: false
  failed_when: false
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s --version

- name: Install k3s agent
  when: (_k3s_version_query.rc != 0)
        or (xronos_k3s_client_version and xronos_k3s_client_version not in _k3s_version_query.stdout)
  block:
    - name: Stat ~/.cache
      register: _cache_folder_query
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.cache"

    - name: Create ~/.cache
      when: not _cache_folder_query.stat.exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.cache"
        state: directory
        mode: u=rwx,g=,o=

    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        dest: "{{ ansible_env.HOME }}/.cache/k3s-install.sh"
        mode: u=rwx,g=rx,o=

    - name: Install k3s agent {{ xronos_k3s_client_version }}
      ansible.builtin.command:
        cmd: |-
          {{ ansible_env.HOME }}/.cache/k3s-install.sh agent
            --node-label host={{ inventory_hostname }}
      environment:
        INSTALL_K3S_VERSION: "{{ xronos_k3s_client_version | default('stable') }}"
        K3S_URL: "{{ xronos_k3s_client_api_endpoint }}"
        K3S_TOKEN: "{{ xronos_k3s_client_token }}"
        K3S_KUBECONFIG_MODE: "0660"

- name: Service k3s-agent start
  become: true
  ansible.builtin.systemd:
    name: k3s-agent
    state: started

- name: Verify k3s installed version
  register: _k3s_version_query
  changed_when: false
  failed_when: _k3s_version_query.rc != 0
              or (xronos_k3s_client_version and xronos_k3s_client_version not in _k3s_version_query.stdout)
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s --version

- name: Create group 
  become: true
  ansible.builtin.group:
    name: k3s
    state: present

- name: Add group k3s to rancher configuration folder
  become: true
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    group: k3s
    mode: u=rwx,g=rwx,o=rx

- name: Stat k3s configuration file
  register: _k3s_config_query
  ansible.builtin.stat:
    path: /etc/rancher/k3s/k3s.yaml

- name: Add group k3s to k3s configuration file
  when: _k3s_config_query.stat.exists
  become: true
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    group: k3s
    mode: u=rw,g=rw,o=
