# SPDX-FileCopyrightText: (c) 2025 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Install k3s-agent
  ansible.builtin.import_tasks: k3s-agent.yml

- name: Configure user {{ ansible_user }} for access to k3s
  ansible.builtin.import_tasks: user.yml
